src/main/java/se/systementor/supershoppen1/shop/model/Subscriber.java

Implement subscriber model

---

src/main/java/se/systementor/supershoppen1/shop/controller/NewsletterController.java
src/main/java/se/systementor/supershoppen1/shop/model/Newsletter.java
src/main/java/se/systementor/supershoppen1/shop/model/NewsletterRepository.java
src/main/java/se/systementor/supershoppen1/shop/services/NewsletterService.java

Controller, repository, service & model
Resolves: STEF-22

Implement the newsletter datatable

---

src/main/java/se/systementor/supershoppen1/shop/controller/NewsletterController.java
src/main/resources/templates/fragments/layouttemplate.html

Implement Newsletters in menu,

---

src/main/resources/templates/admin/newsletters.html

Implement Newsletters template,

---

src/main/java/se/systementor/supershoppen1/shop/controller/NewsletterController.java
src/main/java/se/systementor/supershoppen1/shop/model/Newsletter.java
src/main/java/se/systementor/supershoppen1/shop/services/NewsletterService.java

Update newsletter template

---

src/main/resources/templates/fragments/layouttemplate.html

Implement newsletter signup toggle

---

src/main/java/se/systementor/supershoppen1/shop/controller/NewsletterController.java
src/main/resources/templates/admin/newsletters.html
src/main/resources/templates/admin/send-newsletter.html

Implement newsletter popup as admin

---

src/main/java/se/systementor/supershoppen1/shop/controller/GlobalUsageController.java
src/main/java/se/systementor/supershoppen1/shop/controller/HomeController.java
src/main/resources/templates/fragments/layouttemplate.html

Hides subscriber window if the user is signed in
and has subscribed to the newsletter.
Resolves: STEF-26

Implement toggle for subscriber window

---

src/main/java/se/systementor/supershoppen1/shop/configuration/WebSecurityConfig.java
src/main/java/se/systementor/supershoppen1/shop/controller/AdminController.java
src/main/java/se/systementor/supershoppen1/shop/controller/HomeController.java
src/main/java/se/systementor/supershoppen1/shop/controller/SubscriberController.java
src/main/java/se/systementor/supershoppen1/shop/model/Subscriber.java
src/main/java/se/systementor/supershoppen1/shop/services/SubscriberService.java
src/main/resources/templates/admin/newsletters.html
src/main/resources/templates/fragments/layouttemplate.html
src/main/resources/templates/home.html
src/main/resources/templates/login.html

Pasted in the original code for login.html and login.html,adjusted the save controller in SubscriberController and layouttemplate.html. layouttemplate.html doesn't include the authentication code that Love wrote but can be added later. Non users can subscribe to the newsletter and the field cannot be empty when you click the subscribe button.

Add Subscriber

---

src/main/java/se/systementor/supershoppen1/shop/SeedData.java

Fix product duplication bug

---

src/main/java/se/systementor/supershoppen1/shop/controller/SubscriberController.java
src/main/java/se/systementor/supershoppen1/shop/model/NewsletterSubscriberRepository.java
src/main/java/se/systementor/supershoppen1/shop/services/SubscriberService.java

Get subscribers from newsletter

---

src/main/java/se/systementor/supershoppen1/shop/controller/NewsletterController.java
src/main/java/se/systementor/supershoppen1/shop/model/NewsletterRepository.java
src/main/java/se/systementor/supershoppen1/shop/services/NewsletterService.java
src/main/resources/application.properties
src/main/resources/templates/admin/newsletters.html

Added method for deleting drafted newsletters.

Delete drafted newsletters

---

src/main/java/se/systementor/supershoppen1/shop/controller/SubscriberController.java
src/main/resources/templates/fragments/layouttemplate.html
src/main/resources/templates/home.html

Finish newsletter popup

---

src/main/resources/static/css/style.css
src/main/resources/templates/admin/edit-newsletter.html
src/main/resources/templates/admin/newsletters.html
src/main/resources/templates/admin/send-newsletter.html

Made the newsletter (and newsletter edit)  a little prettier through some lovely css.

Newsletter frontend

---

pom.xml

Add dependancy for email sender

---

src/main/java/se/systementor/supershoppen1/shop/configuration/MailSenderConfiguration.java
src/main/resources/application-production.properties
src/main/resources/application.properties

Todos added for when smtp info is avelable.
Resolves: STEF-51

Add mail server properties

---

src/main/java/se/systementor/supershoppen1/shop/controller/GlobalUsageController.java

Illegal state when auth is null.

Implement null check for auth

---

src/main/resources/application-production.properties

Implement mail trap support

---

src/main/java/se/systementor/supershoppen1/shop/controller/HomeController.java
src/main/resources/templates/fragments/layouttemplate.html

in backened & frontend. Resolves STEF-56 and STEF-57

Added krisinformation API,

---

src/main/java/se/systementor/supershoppen1/shop/controller/ContactController.java
src/main/java/se/systementor/supershoppen1/shop/model/Contact.java
src/main/java/se/systementor/supershoppen1/shop/model/ContactRepository.java
src/main/java/se/systementor/supershoppen1/shop/services/ContactService.java
src/main/resources/templates/contact.html
src/main/resources/templates/fragments/layouttemplate.html

Added frontend page for Contact form

Contact form Frontend

---

pom.xml
src/main/java/se/systementor/supershoppen1/shop/controller/ContactController.java
src/main/java/se/systementor/supershoppen1/shop/controller/EmailController.java
src/main/java/se/systementor/supershoppen1/shop/controller/SubscriberController.java
src/main/java/se/systementor/supershoppen1/shop/services/EmailService.java
src/main/java/se/systementor/supershoppen1/shop/services/EmailServiceImpl.java
src/main/resources/application-dev.properties
src/main/resources/templates/contact.html
src/test/java/se/systementor/supershoppen1/shop/services/EmailServiceTest.java
src/test/java/se/systementor/supershoppen1/shop/services/SubscriberServiceTest.java

New connect emailservice

---

src/main/java/se/systementor/supershoppen1/shop/controller/HomeController.java

getKrisInfo now fetches from the API and updates once every hour (thx Oggi). Also shows Krisinformation on every page on the site. Resolves STEF-59

Added dataCache function
